# ios/Podfile
platform :ios, '10.0'

target 'RNAnalyticsTools' do
  pod 'Firebase/Analytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKAppEvents'
  pod 'AppsFlyerFramework'
  pod 'Branch'
end
